// Code generated by hack/scripts/generate_plugin_go_sdk.py. DO NOT EDIT.
// Source: api/plugin/v1/*.proto

package pluginapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

type PluginDiagnosticsServiceClient interface {
	ListInteractionLogs(ctx context.Context, in *ListInteractionLogsRequest, opts ...grpc.CallOption) (*ListInteractionLogsResponse, error)
	GetMetricsSnapshot(ctx context.Context, in *GetMetricsSnapshotRequest, opts ...grpc.CallOption) (*GetMetricsSnapshotResponse, error)
	GetDiagnosticSnapshot(ctx context.Context, in *GetDiagnosticSnapshotRequest, opts ...grpc.CallOption) (*GetDiagnosticSnapshotResponse, error)
}

type pluginDiagnosticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginDiagnosticsServiceClient(cc grpc.ClientConnInterface) PluginDiagnosticsServiceClient {
	return &pluginDiagnosticsServiceClient{cc}
}

func (c *pluginDiagnosticsServiceClient) ListInteractionLogs(ctx context.Context, in *ListInteractionLogsRequest, opts ...grpc.CallOption) (*ListInteractionLogsResponse, error) {
	out := new(ListInteractionLogsResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.PluginDiagnosticsService/ListInteractionLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginDiagnosticsServiceClient) GetMetricsSnapshot(ctx context.Context, in *GetMetricsSnapshotRequest, opts ...grpc.CallOption) (*GetMetricsSnapshotResponse, error) {
	out := new(GetMetricsSnapshotResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.PluginDiagnosticsService/GetMetricsSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginDiagnosticsServiceClient) GetDiagnosticSnapshot(ctx context.Context, in *GetDiagnosticSnapshotRequest, opts ...grpc.CallOption) (*GetDiagnosticSnapshotResponse, error) {
	out := new(GetDiagnosticSnapshotResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.PluginDiagnosticsService/GetDiagnosticSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type PluginDiagnosticsServiceServer interface {
	ListInteractionLogs(context.Context, *ListInteractionLogsRequest) (*ListInteractionLogsResponse, error)
	GetMetricsSnapshot(context.Context, *GetMetricsSnapshotRequest) (*GetMetricsSnapshotResponse, error)
	GetDiagnosticSnapshot(context.Context, *GetDiagnosticSnapshotRequest) (*GetDiagnosticSnapshotResponse, error)
}

type UnimplementedPluginDiagnosticsServiceServer struct{}

func (UnimplementedPluginDiagnosticsServiceServer) ListInteractionLogs(context.Context, *ListInteractionLogsRequest) (*ListInteractionLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInteractionLogs not implemented")
}

func (UnimplementedPluginDiagnosticsServiceServer) GetMetricsSnapshot(context.Context, *GetMetricsSnapshotRequest) (*GetMetricsSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetricsSnapshot not implemented")
}

func (UnimplementedPluginDiagnosticsServiceServer) GetDiagnosticSnapshot(context.Context, *GetDiagnosticSnapshotRequest) (*GetDiagnosticSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiagnosticSnapshot not implemented")
}

func RegisterPluginDiagnosticsServiceServer(s grpc.ServiceRegistrar, srv PluginDiagnosticsServiceServer) {
	s.RegisterService(&PluginDiagnosticsService_ServiceDesc, srv)
}

func _PluginDiagnosticsService_ListInteractionLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInteractionLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDiagnosticsServiceServer).ListInteractionLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.PluginDiagnosticsService/ListInteractionLogs"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDiagnosticsServiceServer).ListInteractionLogs(ctx, req.(*ListInteractionLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginDiagnosticsService_GetMetricsSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDiagnosticsServiceServer).GetMetricsSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.PluginDiagnosticsService/GetMetricsSnapshot"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDiagnosticsServiceServer).GetMetricsSnapshot(ctx, req.(*GetMetricsSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginDiagnosticsService_GetDiagnosticSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagnosticSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginDiagnosticsServiceServer).GetDiagnosticSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.PluginDiagnosticsService/GetDiagnosticSnapshot"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginDiagnosticsServiceServer).GetDiagnosticSnapshot(ctx, req.(*GetDiagnosticSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var PluginDiagnosticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flypig.plugin.v1.PluginDiagnosticsService",
	HandlerType: (*PluginDiagnosticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "ListInteractionLogs", Handler: _PluginDiagnosticsService_ListInteractionLogs_Handler},
		{MethodName: "GetMetricsSnapshot", Handler: _PluginDiagnosticsService_GetMetricsSnapshot_Handler},
		{MethodName: "GetDiagnosticSnapshot", Handler: _PluginDiagnosticsService_GetDiagnosticSnapshot_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/plugin/v1/diagnostics.proto",
}

type CollectorPluginServiceClient interface {
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*LifecycleResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*LifecycleResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*LifecycleResponse, error)
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*LifecycleResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*LifecycleResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	ApplyTasks(ctx context.Context, in *ApplyTasksRequest, opts ...grpc.CallOption) (*ApplyTasksResponse, error)
	StopTasks(ctx context.Context, in *StopTasksRequest, opts ...grpc.CallOption) (*StopTasksResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	DiscoverDevices(ctx context.Context, in *DiscoverDevicesRequest, opts ...grpc.CallOption) (*DiscoverDevicesResponse, error)
	DiscoverPoints(ctx context.Context, in *DiscoverPointsRequest, opts ...grpc.CallOption) (*DiscoverPointsResponse, error)
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*CollectResponse, error)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (CollectorPluginService_StreamEventsClient, error)
	AckEvents(ctx context.Context, in *AckEventsRequest, opts ...grpc.CallOption) (*AckEventsResponse, error)
}

type collectorPluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorPluginServiceClient(cc grpc.ClientConnInterface) CollectorPluginServiceClient {
	return &collectorPluginServiceClient{cc}
}

func (c *collectorPluginServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Handshake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/ValidateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*LifecycleResponse, error) {
	out := new(LifecycleResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*LifecycleResponse, error) {
	out := new(LifecycleResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*LifecycleResponse, error) {
	out := new(LifecycleResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*LifecycleResponse, error) {
	out := new(LifecycleResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Reload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*LifecycleResponse, error) {
	out := new(LifecycleResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) ApplyTasks(ctx context.Context, in *ApplyTasksRequest, opts ...grpc.CallOption) (*ApplyTasksResponse, error) {
	out := new(ApplyTasksResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/ApplyTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) StopTasks(ctx context.Context, in *StopTasksRequest, opts ...grpc.CallOption) (*StopTasksResponse, error) {
	out := new(StopTasksResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/StopTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/ListTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) DiscoverDevices(ctx context.Context, in *DiscoverDevicesRequest, opts ...grpc.CallOption) (*DiscoverDevicesResponse, error) {
	out := new(DiscoverDevicesResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/DiscoverDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) DiscoverPoints(ctx context.Context, in *DiscoverPointsRequest, opts ...grpc.CallOption) (*DiscoverPointsResponse, error) {
	out := new(DiscoverPointsResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/DiscoverPoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*CollectResponse, error) {
	out := new(CollectResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/Collect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/ExecuteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorPluginServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (CollectorPluginService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CollectorPluginService_ServiceDesc.Streams[0], "/flypig.plugin.v1.CollectorPluginService/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorPluginServiceStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CollectorPluginService_StreamEventsClient interface {
	Recv() (*EventBatch, error)
	grpc.ClientStream
}

type collectorPluginServiceStreamEventsClient struct{ grpc.ClientStream }

func (x *collectorPluginServiceStreamEventsClient) Recv() (*EventBatch, error) {
	m := new(EventBatch)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *collectorPluginServiceClient) AckEvents(ctx context.Context, in *AckEventsRequest, opts ...grpc.CallOption) (*AckEventsResponse, error) {
	out := new(AckEventsResponse)
	err := c.cc.Invoke(ctx, "/flypig.plugin.v1.CollectorPluginService/AckEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type CollectorPluginServiceServer interface {
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	Init(context.Context, *InitRequest) (*LifecycleResponse, error)
	Start(context.Context, *StartRequest) (*LifecycleResponse, error)
	Stop(context.Context, *StopRequest) (*LifecycleResponse, error)
	Reload(context.Context, *ReloadRequest) (*LifecycleResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*LifecycleResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	ApplyTasks(context.Context, *ApplyTasksRequest) (*ApplyTasksResponse, error)
	StopTasks(context.Context, *StopTasksRequest) (*StopTasksResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	DiscoverDevices(context.Context, *DiscoverDevicesRequest) (*DiscoverDevicesResponse, error)
	DiscoverPoints(context.Context, *DiscoverPointsRequest) (*DiscoverPointsResponse, error)
	Collect(context.Context, *CollectRequest) (*CollectResponse, error)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	StreamEvents(*StreamEventsRequest, CollectorPluginService_StreamEventsServer) error
	AckEvents(context.Context, *AckEventsRequest) (*AckEventsResponse, error)
}

type UnimplementedCollectorPluginServiceServer struct{}

func (UnimplementedCollectorPluginServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Info(context.Context, *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}

func (UnimplementedCollectorPluginServiceServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateConfig not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Init(context.Context, *InitRequest) (*LifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Start(context.Context, *StartRequest) (*LifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Stop(context.Context, *StopRequest) (*LifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Reload(context.Context, *ReloadRequest) (*LifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Shutdown(context.Context, *ShutdownRequest) (*LifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func (UnimplementedCollectorPluginServiceServer) ApplyTasks(context.Context, *ApplyTasksRequest) (*ApplyTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyTasks not implemented")
}

func (UnimplementedCollectorPluginServiceServer) StopTasks(context.Context, *StopTasksRequest) (*StopTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTasks not implemented")
}

func (UnimplementedCollectorPluginServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}

func (UnimplementedCollectorPluginServiceServer) DiscoverDevices(context.Context, *DiscoverDevicesRequest) (*DiscoverDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverDevices not implemented")
}

func (UnimplementedCollectorPluginServiceServer) DiscoverPoints(context.Context, *DiscoverPointsRequest) (*DiscoverPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoverPoints not implemented")
}

func (UnimplementedCollectorPluginServiceServer) Collect(context.Context, *CollectRequest) (*CollectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Collect not implemented")
}

func (UnimplementedCollectorPluginServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}

func (UnimplementedCollectorPluginServiceServer) StreamEvents(*StreamEventsRequest, CollectorPluginService_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}

func (UnimplementedCollectorPluginServiceServer) AckEvents(context.Context, *AckEventsRequest) (*AckEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckEvents not implemented")
}

func RegisterCollectorPluginServiceServer(s grpc.ServiceRegistrar, srv CollectorPluginServiceServer) {
	s.RegisterService(&CollectorPluginService_ServiceDesc, srv)
}

func _CollectorPluginService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Handshake"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Info"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/ValidateConfig"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Init"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Start"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Stop"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Reload"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Shutdown"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Health"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Status"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_ApplyTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).ApplyTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/ApplyTasks"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).ApplyTasks(ctx, req.(*ApplyTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_StopTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).StopTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/StopTasks"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).StopTasks(ctx, req.(*StopTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/ListTasks"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_DiscoverDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).DiscoverDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/DiscoverDevices"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).DiscoverDevices(ctx, req.(*DiscoverDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_DiscoverPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).DiscoverPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/DiscoverPoints"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).DiscoverPoints(ctx, req.(*DiscoverPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_Collect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).Collect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/Collect"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).Collect(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/ExecuteCommand"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_AckEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorPluginServiceServer).AckEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/flypig.plugin.v1.CollectorPluginService/AckEvents"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorPluginServiceServer).AckEvents(ctx, req.(*AckEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorPluginService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorPluginServiceServer).StreamEvents(m, &collectorPluginServiceStreamEventsServer{stream})
}

type CollectorPluginService_StreamEventsServer interface {
	Send(*EventBatch) error
	grpc.ServerStream
}

type collectorPluginServiceStreamEventsServer struct{ grpc.ServerStream }

func (x *collectorPluginServiceStreamEventsServer) Send(m *EventBatch) error {
	return x.ServerStream.SendMsg(m)
}

var CollectorPluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flypig.plugin.v1.CollectorPluginService",
	HandlerType: (*CollectorPluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Handshake", Handler: _CollectorPluginService_Handshake_Handler},
		{MethodName: "Info", Handler: _CollectorPluginService_Info_Handler},
		{MethodName: "ValidateConfig", Handler: _CollectorPluginService_ValidateConfig_Handler},
		{MethodName: "Init", Handler: _CollectorPluginService_Init_Handler},
		{MethodName: "Start", Handler: _CollectorPluginService_Start_Handler},
		{MethodName: "Stop", Handler: _CollectorPluginService_Stop_Handler},
		{MethodName: "Reload", Handler: _CollectorPluginService_Reload_Handler},
		{MethodName: "Shutdown", Handler: _CollectorPluginService_Shutdown_Handler},
		{MethodName: "Health", Handler: _CollectorPluginService_Health_Handler},
		{MethodName: "Status", Handler: _CollectorPluginService_Status_Handler},
		{MethodName: "ApplyTasks", Handler: _CollectorPluginService_ApplyTasks_Handler},
		{MethodName: "StopTasks", Handler: _CollectorPluginService_StopTasks_Handler},
		{MethodName: "ListTasks", Handler: _CollectorPluginService_ListTasks_Handler},
		{MethodName: "DiscoverDevices", Handler: _CollectorPluginService_DiscoverDevices_Handler},
		{MethodName: "DiscoverPoints", Handler: _CollectorPluginService_DiscoverPoints_Handler},
		{MethodName: "Collect", Handler: _CollectorPluginService_Collect_Handler},
		{MethodName: "ExecuteCommand", Handler: _CollectorPluginService_ExecuteCommand_Handler},
		{MethodName: "AckEvents", Handler: _CollectorPluginService_AckEvents_Handler},
	},
	Streams: []grpc.StreamDesc{
		{StreamName: "StreamEvents", Handler: _CollectorPluginService_StreamEvents_Handler, ServerStreams: true},
	},
	Metadata: "api/plugin/v1/plugin.proto",
}
